#!/usr/bin/env bash
# Simple script to view the local audit log.

PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
AUDIT_LOG_FILE="$PROJECT_ROOT/.claude/state/audit.log"

if [[ -f "$AUDIT_LOG_FILE" ]]; then
  echo "--- YAMTAM ENGINE Audit Log ---"
  cat "$AUDIT_LOG_FILE"
else
  echo "No audit log found at $AUDIT_LOG_FILE."
  echo "Audit logs are generated by .claude/hooks/audit-log.sh after tool usage."
fi
